example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_film
from mywatchlist.views import show_xml 
from mywatchlist.views import show_json
from mywatchlist.views import show_xml_by_id
from mywatchlist.views import show_json_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_film, name='show_film'),
    path('html/', show_film, name='show_film'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),

]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import show_json
from todolist.views import toggle
from todolist.views import delete

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='createtask'),
    path('json/', show_json, name='show_json'),
    path('toggle-task/<int:id>', toggle, name='toggle'),
    path('delete-task/<int:id>', delete, name='delete'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class Film(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class task(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from django import forms
from todolist.models import task

class taskform(forms.ModelForm):
    class Meta:
        model = task
        fields = {"title", "description"}

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang' : data_barang_katalog,
        'nama' : 'Abby Marvel',
        'id' : '2106751796',
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from typing import Counter
from django.shortcuts import render
from mywatchlist.models import Film
from django.http import HttpResponse
from django.core import serializers

def show_status(request):
    data_film = Film.objects.all()
    counter=0
    for data in data_film:
        if data.watched == True:
            counter+=1
    
    if counter >= len(data_film)-counter:
        return "Selamat, kamu sudah banyak menonton!"
    else:
        return "Wah, kamu masih sedikit menonton!"

def show_film(request):
    data_film = Film.objects.all()

    context = {
        'list_film' : data_film,
        'nama' : 'Abby Marvel',
        'id' : '2106751796',
        'status' : show_status(request),
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = Film.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Film.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Film.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Film.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.urls import reverse
from django.shortcuts import render
from todolist.models import task
from todolist.forms import taskform
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

@login_required(login_url='/todolist/login/')

def show_todolist(request):
    data_todolist = task.objects.filter(user=request.user)
    context = {
    'list_todo': data_todolist,
    'nama': request.user,
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def create_task(request):
    if request.method == "POST":
        form = taskform(request.POST)
        form.instance.user = request.user
        form.instance.date = datetime.datetime.now()
        if form.is_valid():
            form.save()
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            return response
    else:
        form = taskform()

    context = {'form':form}
    return render(request, 'createtask.html', context)

def toggle(request, id):
    data = task.objects.get(pk = id)
    data.is_finished = not data.is_finished
    data.save()
    response = HttpResponseRedirect(reverse("todolist:show_todolist"))
    return response

def delete(request, id):
    data = task.objects.get(pk = id)
    data.delete()
    response = HttpResponseRedirect(reverse("todolist:show_todolist"))
    return response

def show_json(request):
    data_todolist = task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data_todolist), content_type="application/json")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}
 <style>
  h1, h5, p {text-align: center;}
  h1, h5, p , th{color: rgb(0, 0, 0);}
  th {text-align: center;}
  tr {background-color: rgba(246, 0, 176, 0.5);}
  div {text-align: center;}
  table, th, td {
    border: 1px solid rgb(14, 13, 13);
  }
  body {
    margin: 0;
    background-color: rgb(12, 255, 150);
    height:100vh;
    color:#fff;
  }
  </style>

  <br>
  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>
  <br>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.item_url}}</th>
      </tr>
  {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}
 <style>
  h1, h5, h2, p {text-align: center;}
  h1, h5, h2, p , th{color: #4D4771}
  th {text-align: center;}
  div {text-align: center;}
  table, th, td {
    border: 1px solid #ffffff;
    background-color: #FF9FB2;
  }
  body {
    margin: 10;
    background-color: #66B9F4;
    height:100vh;
    color:#fff;
  }
  </style>

  <br>
  <h1>🛸 Tugas 3 Assignment PBP/PBD 🕺🏻 </h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>
  <h2>{{status}}</h2>
  <br>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in list_film %}
    <tr>
        <th>{{film.watched}}</th>
        <th>{{film.title}}</th>
        <th>{{film.rating}}</th>
        <th>{{film.release_date}}</th>
        <th>{{film.review}}</th>
      </tr>
  {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/createtask.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}  

<style>
    h1, h3, h2, p {text-align: center;}
    h1, h3, h2, p , th{color: #4D4771}
    th {text-align: center;}
    div {text-align: center;}
    
    table, th, td {
        background-color: #5C95FF;
        text-align: center;
        border-radius: 5px;
    }
    body {
      margin: 10;
      background-color: #66B9F4;
      height:100vh;
      color:#fff;
    }



    input.btn.post-btn {
        outline: none;
        border: none;
        cursor: pointer;
        display: inline-block;
        margin: 0 auto;
        text-align: center;
        background-color: #47AB11;
        color: #fff;
        border-radius: 4px;
        box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.16);
        font-size: 17px;
    }

    button.cancel-btn {
        outline: none;
        border: none;
        cursor: pointer;
        display: inline-block;
        margin: 0 auto;
        text-align: center;
        background-color: #d21b1b;
        color: #ffffff;
        border-radius: 4px;
        box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.16);
        font-size: 17px;
    }
    </style>

<h1>Eby's Task Manager</h1>
<h3>Create Task</h3>

    <form method="POST" >  
        {% csrf_token %}  
        <table align="center">  
            <tr>
                <td>Title: </td>
                <td>{{form.title}}</td>
            </tr>
                    
            <tr>
                <td>Description: </td>
                <td>{{form.description}}</td>
            </tr>
            <tr>
                <td>
                    <th><input class="btn post-btn" type="submit" value="Post"></th>
                    <th><button class="cancel-btn"><a href="{% url 'todolist:show_todolist' %}" style="color:rgb(255, 255, 255); text-decoration: none">Cancel</a></button></th>
                </td>
            </tr>
        </table>  
    </form>

{% if messages %}  
    <ul>   
        {% for message in messages %}  
            <li>{{ message }}</li>  
            {% endfor %}  
    </ul>   
{% endif %}

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    h1, h5, h2, p {text-align: center;}
    h1, h5, h2, p , th{color: #4D4771}
    th {text-align: center;}
    div {text-align: center;}
    
    table, th, td {
      background-color: #5C95FF;
      text-align: center;
      border-radius: 5px;
    }

    body {
    margin: 10;
    background-color: #B9E6FF;
    height:100vh;
    color:#2E2D4D;
    font-family: 'Lato', sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    overflow: hidden;
    margin: 0;
    padding: 0;
    }
    
    table {
        border-style: double;
        border-color: #2E2D4D;
    }


    input.btn.login_btn {
        outline: none;
        border: none;
        cursor: pointer;
        display: inline-block;
        margin: 0 auto;
        text-align: center;
        background-color: #47AB11;
        color: #fff;
        border-radius: 4px;
        box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.16);
        font-size: 17px;
    }
    
    </style>

<div class = "login">
    <h1>Eby's Task Manager</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table align="center">
            <tr>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <th><input class="btn login_btn" type="submit" value="Login"></th>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <h3>Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a> </h3>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}

<style>
    h1, h3, h2, p {text-align: center;}
    h1, h3, h2, p , th{color: #4D4771}
    th {text-align: center;}
    div {text-align: center;}
    
    table, th, td {
      background-color: #5C95FF;
      text-align: center;
      border-radius: 5px;
    }

    body {
    margin: 10;
    background-color: #B9E6FF;
    height:100vh;
    color:#2E2D4D;
    font-family: 'Lato', sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    overflow: hidden;
    margin: 0;
    padding: 0;
    }

    input.btn.submit_btn {
        outline: none;
        border: none;
        cursor: pointer;
        display: inline-block;
        margin: 0 auto;
        text-align: center;
        background-color: #47AB11;
        color: #fff;
        border-radius: 4px;
        box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.16);
        font-size: 17px;
    }
    
    </style>

<div class = "login">
    
    <h1>Eby's Task Manager</h1>  

    <h3>Formulir Registrasi</h3>

        <form method="POST" >  
            {% csrf_token %}  
            <table align="center">  
                {{ form.as_table }}  
                <tr>
                    <td>
                        <th><input class="btn submit_btn" type="submit" value="submit"></th>
                    </td>
                </tr>
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
  $(document).ready(() => {
    console.log("test");
    tasks();
  })
  
  function tasks() {
    console.log("in getTasks")
    $.ajax({
      type: "GET",
      url: "/todolist/json",
    }).done((data) => {
      console.log("about to showTasks")
      showTasks(data)
    });
  }

  function showTasks(data) {
    console.log("in showTasks");
    const cards = $('.cards');
    cards.empty();
    data.forEach(task => {
      const card = `
        <li class="card">
          <div>
            <h3 class="card-title" align="center">${task.fields.title}</h3>
            <p>${task.fields.description}</p>
            <h6 class="card-date" align="center">${task.fields.date}</h6>
            <h6 align="center">${task.fields.is_finished ? "Finished" : "Not Finished"}</h6>
            <div class="card-link-wrapper" align="center">
              <button class="btn btn-primary" type="submit" value="Toggle" onclick=toggleTask(${task.pk})><i></i>Toggle</button>
              <button class="btn btn-danger" type="submit" value="Delete" onclick=deleteTask(${task.pk})><i></i>Delete</button>
            </div>
            <p></p>
          </div>
        </li>
        <p></p>`;
      cards.append(card);
    })
  }

  function toggleTask(id) {
    $.ajax({
      type: "GET",
      url: "/todolist/toggle-task/" + id,
    }).done((data) => {
      tasks();
    })
  }  

  function deleteTask(id) {
    $.ajax({
      type: "GET",
      url: "/todolist/delete-task/" + id,
    }).done((data) => {
      tasks();
    })
  }

  function createTasks() {
    const form = $('.newtask');
    $.ajax({
      type: "POST",
      url: "/todolist/create-task/",
      data: form.serialize(),
    }).done(function (data) {
      console.log("task?")
      form.trigger("reset");
      tasks();
    })
    $("#staticBackdrop").modal("hide");
  }



</script>



<style>
  h1, h5, h2, h4, h3, p {text-align: center;}
  h1, h5, h2, h4, h3, p , th{color: #4D4771}
  th {text-align: center;}

a {
  color: #FFFFFF;
  text-align: center;
}

tr {background-color: rgba(120, 69, 46, 0.91);}

body{
  margin: 10;
  background-color: #B9E6FF;
  color:#2E2D4D;
  display: grid;
  justify-content: center;
  align-items: center;
  overflow: hidden;
}

.ukuranNama{
  font-size: 25px;
}

.button{
  align-items: center;
}

.login_btn{
  outline: none;
      border: none;
      cursor: pointer;
      display: inline-block;
      margin: 0 auto;
      text-align: center;
      background-color: #444444;
      color: #fff;
      border-radius: 5px;
      box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.16);
      font-size: 17px;
}

  .card {
    /* Add shadows to create the "card" effect */
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border-radius: 10px;
  }

  /* On mouse-over, add a deeper shadow */
  .card:hover {
    box-shadow: 0 10px 16px 0 rgba(0, 0, 0, 0.743);
  }

  /* Add some padding inside the card container */
  .container {
    padding: 2px 16px;
  }

  *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
  }

  ul{
    list-style-type: none;
    margin: 0;
    padding: 0;
  }

  header{
    background-color: #262626;
  }

  li{
      list-style: none;
  }

  a{
      color: white;
      text-decoration: none;
  }

  .navbar{
      min-height: 70px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 0 24px;
  }


  .navMenu{
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 60px;
  }

  .nav-branding{
      font-size: 2rem;
  }

  .list-link{
      transition: 0.7s ease;
  }

  .list-link:hover{
      color: #a767e5;
  }


</style>

  <header>
    <nav class="navbar">
        <a href="#" class="nav-branding">AM.</a>
        <ul class="navMenu">
            <li class="nav-item">
            <a href="#" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Create Task</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'todolist:logout' %}">Logout</a>
            </li>
        </ul>
    </nav>
  </header>

  <h1>Eby's Task Manager</h1>
  <h2>Hallo {{user}}!</h2>


<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <h1 style="font-weight: bold;"class="modal-title fs-5" id="staticBackdropLabel">Create new task</h1>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <div class="task-form">
        <form class="newtask" id="form">
          {% csrf_token %}
          <input id="title" type="text" name="title" placeholder="Title"></input>
          <p></p>
          <textarea id="description" type="text" name="description" placeholder="Description"></textarea>
        </form>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <button id="button" type="submit" class="btn btn-success" onclick=createTasks()>Create new task</button>
    </div>
  </div>
</div>
</div>

<ul class="cards" id="cards"></ul>
  <h4>Sesi terakhir login: {{ last_login }}</h4>

 {% endblock content %}